language: python
python:
- "3.6"
- "3.7"
- "3.8"
install:
- pip install -U pip setuptools wheel
- pip install -U poetry
- poetry install
script:
- poetry run pytest --cov=pinnwand
after_script:
- bash <(curl -s https://codecov.io/bash)
